---
title: "Mini-Project 2"
author: "Ester Zhao, Lizette Carpenter, and Emily Kim"
date: "March 23, 2017"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)
library(gridExtra)

```

```{r, include = FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
cand_info <- candidates %>%
  select(cand_id, cand_party_affiliation, cand_office, cand_election_yr) %>%
  filter( cand_office == "S"| cand_office == "H",
         cand_election_yr >= 2008 &
           cand_election_yr <= 2016) %>%
  arrange(cand_election_yr) %>%
  arrange(cand_office)

cand_contributions <- contributions %>%
  select(name, cand_id, transaction_amt) %>%
  filter(cand_id != "") %>%
  arrange(cand_id)

total_cand_contrib <- cand_contributions %>%
  group_by(cand_id) %>%
  summarise(total = sum(transaction_amt), n = n()) 

join_tbl <- total_cand_contrib %>%
  left_join(cand_info, cand_contributions, by = NULL, copy = FALSE, suffix = c(".cand_info", ".cand_con")) %>%
  filter(!is.na(cand_election_yr), 
         cand_party_affiliation != "" ) %>%
  arrange(cand_election_yr)

final_tbl <- join_tbl %>%
  filter(cand_party_affiliation == "DEM" | cand_party_affiliation == "REP") %>%
  filter(cand_election_yr != 2009 & cand_election_yr != 2011) %>%
  group_by(cand_election_yr, cand_party_affiliation, cand_office ) %>%
  summarise(total_contrib = sum(total), n = n())
  
```

```{r}
ggplot(final_tbl, aes(x = cand_election_yr, 
                      y = total_contrib)) +
  labs( x = "Election Year",
        y = "Total Contribution ($)") +
  ggtitle("Insert Title") +
  geom_line() +
  geom_point(aes(color = cand_party_affiliation)) 
  
```

```{r}
l_years = c(2008, 2010, 2012, 2014, 2016)
```

```{r}
yearly_contrib <- function(year_arg) {
  cand_info <- candidates %>%
  select(cand_id, cand_party_affiliation, cand_office, cand_election_yr) %>%
  filter( cand_office == "S"| cand_office == "H") %>%
  filter( cand_election_yr == year_arg) %>%
  arrange(cand_election_yr) %>%
  arrange(cand_office)

  cand_contributions <- contributions %>%
    select(name, cand_id, transaction_amt) %>%
    filter(cand_id != "") %>%
    arrange(cand_id)
  
  total_cand_contrib <- cand_contributions %>%
    group_by(cand_id) %>%
    summarise(total = sum(transaction_amt), n = n()) 
  
  join_tbl <- total_cand_contrib %>%
    left_join(cand_info, cand_contributions, by = NULL, copy = FALSE, suffix = c(".cand_info", ".cand_con")) %>%
    filter(!is.na(cand_election_yr), 
           cand_party_affiliation != "" ) %>%
    arrange(cand_election_yr)
  
  final_tbl <- join_tbl %>%
    filter(cand_party_affiliation == "DEM" | cand_party_affiliation == "REP") %>%
    filter( cand_election_yr == year_arg) %>%
    group_by(cand_election_yr, cand_party_affiliation, cand_office) %>%
    summarise(total_contrib = sum(total), n = n())
  
  ggplot(final_tbl, aes(x = cand_party_affiliation, 
                        y = total_contrib)) +
    geom_bar(stat = "identity", 
             aes(fill = cand_office)) +
    ggtitle(year_arg) + 
    scale_fill_manual(name = "Candidate Office", 
                        labels = c("House", "Senate"),
                        values = c("#66CC99", "#9999CC")) + 
    labs( x = "Party Affiliation",
          y = "Total Contributions ($)") 
}
plots <- lapply(l_years, FUN = yearly_contrib)
do.call("grid.arrange", c(plots, ncol = 2))
```
